sudo: false

language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer config -g github-oauth.github.com $COMPOSER_TOKEN
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s build/logs/ https://codecov.io/bash)
