name: CI

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 7.4, 8.1 ]
        laravel: [ 6.20, 10.14 ]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php }}"

      - name: Force Laravel version
        run: composer require illuminate/view:${{ matrix.laravel }} --no-interaction --no-update

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          version: ${{ matrix.php == 7.4 && '9' || 'latest'}}
          php_version: "${{ matrix.php }}"
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml

      - name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: coverage.xml
